todo_project/todo_app/urls.py
from django.urls import path
from todo_app import views
app_name = 'todo_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert', views.insert, name='insert'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('login', views.auth_login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.auth_logout, name='logout')
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo_app.urls')),
    path('admin/', admin.site.urls),
    
]

todo_project/todo_app/models.py
from django.db import models
from django.conf import settings

class todo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    
    subject = models.CharField("subject", max_length=50)
    extra = models.TextField("extra", max_length=500)
    
    HIGHPRIO = 'H'
    MEDUIMPRIO = 'M'
    LOWPRIO = 'L'
    PRIORITY_CHOICES=[
        (HIGHPRIO, 'highPriority'),
        (MEDUIMPRIO, 'meduimPriority'),
        (LOWPRIO, 'lowPriority')
    ]
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, default=MEDUIMPRIO)
    
    date = models.DateTimeField("date time", null=True)
    
    date_pub = models.DateField("date published", auto_now_add=True)
    date_upd = models.DateField("date updated", auto_now=True)
    
    
    
    def __str__(self):
        return self.subject
    

# Create your models here.

todo_project/todo_app/views.py
from django.shortcuts import render, get_object_or_404
from todo_app.models import todo
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from django.views.decorators.http import require_http_methods
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def index(request):
    if request.user.is_authenticated:
        # list = todo.objects.all().values()
        # list = get_object_or_404(todo, pk=request.user.id)
        list = todo.objects.filter(user=request.user.id).values()
        
        print(list)
        return render(request, 'index.html', {'todo_list':list})
    return HttpResponseRedirect(reverse('todo_app:login'))
   
def insert(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("todo_app:login"))
    if request.method == "GET":
        return render(request, 'insert.html')
    elif request.method == "POST":
        sub = request.POST['Subject']
        ext = request.POST['extra']
        # request.POST['date'] => 03/09/2023 9:17 AM
        dat = datetime.strptime(request.POST['date'], "%m/%d/%Y %I:%M %p") 
        todo(user=request.user ,subject=sub, extra=ext, date=dat).save()
        return HttpResponseRedirect(reverse('todo_app:index'))

def update(request,id):
    todo_up = get_object_or_404(todo, pk=id)
    if request.method == "GET":
        # todo_up.date => March 9, 2023, 9:17 a.m.
        if (todo_up.date == None):
            return render(request, 'update.html', {'todo':todo_up, 'date':None})
        else:
            date = datetime.strftime(todo_up.date, '%m/%d/%Y %I:%M %p')
            return render(request, 'update.html', {'todo':todo_up, 'date':date})
    elif request.method == "POST":
        todo_up.subject = request.POST['Subject']
        todo_up.extra = request.POST['extra']
        # request.POST['date'] => 03/09/2023 9:17 AM
        date = request.POST['date']
        if date is not None and not date == '':
            todo_up.date = datetime.strptime(date, "%m/%d/%Y %I:%M %p") 
        todo_up.save()
        return HttpResponseRedirect(reverse('todo_app:index'))

def delete(request, id):
    todo_del = get_object_or_404(todo, pk=id)
    todo_del.delete()
    return HttpResponseRedirect(reverse('todo_app:index'))

def auth_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('todo_app:index'))
    mess = ""
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('todo_app:index'))
        elif user is not None and not user.is_active:
            # to allow deactivated user authenticated I added :
            # AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']
            # to settings.py
            mess = "account is suspended."
        else:
            mess = "Wrong user name or password."
    return render(request, 'login.html', {'message':mess})

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('todo_app:index'))
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        firstname = request.POST.get("firstname")
        lastname = request.POST.get("lastname")
        email = request.POST.get("email")
        user = User.objects.create_user(username, password, email)
        if firstname is not None: user.first_name = firstname
        if lastname is not None: user.last_name = lastname
        user.save()
        return HttpResponseRedirect(reverse('todo_app:login'))
    if request.method == "GET":
        return render(request, "register.html", {})
    
def auth_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('todo_app:login'))
        
        
# Create your views here.

todo_project/todo_app/templates/index.html
{% extends 'master.html' %}
{% block title %}ToDo List{% endblock title %}
{% block content %}
<div id='index-container'>
    {% if todo_list %}
    <table>
        <tr>
            <th>subject</th>
            <th>date published</th>
            <th>date updated</th>
            <th>extra</th>
            <th>priority</th>
            <th>date</th>
            <th>update</th>
            <th>delete</th>
        </tr>
            {% for item in  todo_list %}
            <a>
                <tr>
                    <td>{{ item.subject }}</td>
                    <td>{{ item.date_pub }}</td>
                    <td>{{ item.date_upd }}</td>
                    <td>{{ item.extra }}</td>
                    <td>{{ item.priority }}</td>
                    <td>{{ item.date }}</td>
                    <td><a href='{% url 'todo_app:update' item.id%}'>update</a></td>
                    <td class='deleteBtn' onclick="ask_for_delete('{{ item.subject }}', '{% url 'todo_app:delete' item.id %}')">delete</td>
                </tr>
            </a>
            {% endfor %}
       
    </table>
    {% endif %}
    <span id='add-btn'>
        <a style="display:block;" href='{% url 'todo_app:insert' %}'>New</a>
        <a style="display:block;" href='{% url 'todo_app:logout' %}'>log out</a>
    </span>
</div>
<script>
    function ask_for_delete(subject, url){
        let message = new MessageBox(subject);
        message.setTitle("Delete "+subject);
        message.setMessage('are you sure wanna delete '+subject);
        message
        .addButton("Yes", "green")
        .addButton("No", "red")
        message.show().then((x) => {
            if (x=='Yes'){
                window.location.href = url
                
                let waitMessage = new MessageBox('Wait')
                waitMessage.setTitle('wait')
                waitMessage.setMessage('Wait to delete')
                waitMessage.show()
            }
        })
    }
</script>
{% endblock content %}

todo_project/todo_app/templates/insert.html
{% extends 'master.html' %}
{% block title %}Insert New ToDo{% endblock title %}
{% block content %}
<form method='post' action='{% url 'todo_app:insert' %}'>
    {% csrf_token %}
    <a id='back-btn' href='{% url 'todo_app:index' %}'>
      <i class="fa fa-angle-left" aria-hidden="true"></i>
    </a>
    Subjetct: <input name='Subject'/>
    extra: <input name='extra'/>
    date: <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
        <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1" name="date"/>
        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
    </div>
    <input id="submit" type="submit"/>
</form>
{% endblock content %}

todo_project/todo_app/templates/login.html
{% extends 'master.html' %}
{% block title %}Login{% endblock title %}
{% block content %}
<div>
    <form method="POST" autocomplete="off" action="{% url 'todo_app:login' %}">
        {% csrf_token %}
        <a id='back-btn' href='{% url 'todo_app:index' %}'>
            <i class="fa fa-angle-left" aria-hidden="true"></i>
        </a>
        {% if message %}
            <div id="error">{{ message }}</div>
        {% endif %}
        username:
        <input name="username" type="TEXT" maxlength="20" placeholder="username" autocomplete="cc-number"/>
        password
        <input name="password" type="PASSWORD" maxlength="20" autocomplete="off"/>
        <input type="submit" value="login" id="submit" autocomplete="off"/>
    </form>
</div>
{% endblock content %}

todo_project/todo_app/templates/master.html
<!DOCTYPE html>
<html lang='en'>
<head>

  <!-- LOAD CSS DJAOGN STATIC FILES -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/master.css' %}"/>

  <!-- theme for messagebox scripts -->
  <link rel="stylesheet" href="{% static 'css/messagebox-default.min.css' %}" />

  <!-- script for messagebox Lib -->
  <script src="{% static 'js/messagebox.min.js' %}"></script>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>

  <!-- Bootstrap 4 -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  <!-- Font Awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!-- Moment.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

  <!-- Tempus Dominus Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  <link rel="shortcut icon" type="image/png" href="{% static 'icon/fav.ico' %}"/>
  

<title>{% block title %}{% endblock %}</title>
</head>
<body>
<div id='content'>
{% block content %}
{% endblock %}
</div>
<script>
  $(function () {
    $("#datetimepicker1").datetimepicker();
  });
</script>

</body>
</html>

todo_project/todo_app/templates/register.html
{% extends 'master.html' %}
{% block title %}Login{% endblock title %}
{% block content %}
<div>
    <form id="form" onsubmit="return validation()" method="POST" autocomplete="off" action="{% url 'todo_app:register' %}">
        {% csrf_token %}
        <a id='back-btn' href='{% url 'todo_app:index' %}'>
            <i class="fa fa-angle-left" aria-hidden="true"></i>
        </a>
        username:
        <input name="username" type="TEXT" maxlength="20" placeholder="username" autocomplete="cc-number"/>
        password
        <input name="password" type="PASSWORD" maxlength="20" autocomplete="off"/>
        email:
        <input name="email" type="email" placeholder="email" autocomplete="cc-number"/>
        first name:
        <input name="firstname" type="TEXT" maxlength="20" placeholder="first name" autocomplete="cc-number"/>
        last name:
        <input name="last name" type="TEXT" maxlength="20" placeholder="last name" autocomplete="cc-number"/>
        <input type="submit" value="login" id="submit" autocomplete="off"/>
    </form>
</div>
<script>
    function validation(){
        let form_register = document.getElementById('form')
        for (i=2; i<7; i++){
            if (form_register[i].value == "" ||
                form_register[i].value == null)
                    return false
        }
        return true
    }
</script>
{% endblock content %}

todo_project/todo_app/templates/update.html
{% extends 'master.html' %}
{% block title %}Edit ToDo {{ todo.id }}{% endblock title %}
{% block content %}
    <form method='post' action='{% url 'todo_app:update' todo.id%}'>
        <a id='back-btn' href='{% url 'todo_app:index' %}'>
            <i class="fa fa-angle-left" aria-hidden="true"></i>
          </a>
        {% csrf_token %}
        Subjetct: <input name='Subject' value='{{todo.subject}}'/>
        extra: <input name='extra' value="{{todo.extra}}"/>
        date: <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
            <input type="text" class="form-control datetimepicker-input" 
                data-target="#datetimepicker1" name="date" value="{{date}}"/>
            <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
        </div>
        <input id="submit" type="submit"/>
    </form>
{% endblock content %}